"use client";

import type { ResearchResult, SummarizeResponse } from "@/lib/api";
import { parseResearchMarkdown } from "@/lib/parseResearch";

export interface ResearchReceiptProps {
  result: ResearchResult;
  summary?: SummarizeResponse;
  preIndexed: boolean;
  onClose: () => void;
}

export default function ResearchReceipt({
  result,
  summary,
  preIndexed,
  onClose,
}: ResearchReceiptProps) {
  const provenance = parseResearchMarkdown(result.markdown);

  return (
    <div
      className="fixed inset-0 z-50 flex items-end justify-center bg-ink/40 p-4 sm:items-center"
      role="dialog"
      aria-modal="true"
      aria-labelledby="research-receipt-title"
    >
      <div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded border-[3px] border-ink bg-paper hard-shadow">
        <div className="sticky top-0 flex items-center justify-between border-b-2 border-ink/10 bg-paper px-5 py-4">
          <h2
            id="research-receipt-title"
            className="font-display text-lg font-black tracking-tight"
          >
            Research receipt
          </h2>
          <button
            type="button"
            onClick={onClose}
            className="rounded border-2 border-ink px-2 py-0.5 text-sm font-bold hover:bg-ink hover:text-white"
          >
            Close
          </button>
        </div>

        <div className="space-y-5 px-5 py-5 text-sm">
          <div>
            <p className="font-mono text-[10px] uppercase tracking-wider text-ink/50">
              Topic
            </p>
            <p className="font-display text-xl font-black">{result.keyword}</p>
          </div>

          <div className="flex flex-wrap gap-2">
            <span className="rounded border-2 border-ink bg-white px-2 py-0.5 font-mono text-[10px] font-bold uppercase">
              {preIndexed ? "Pre-indexed" : "Live run"}
            </span>
            {provenance.syncedDate && (
              <span className="rounded border-2 border-ink/30 px-2 py-0.5 font-mono text-[10px] text-ink/60">
                synced {provenance.syncedDate}
              </span>
            )}
          </div>

          <div>
            <p className="font-mono text-[10px] uppercase tracking-wider text-ink/50">
              last30days sources
            </p>
            {provenance.sources.length > 0 ? (
              <p className="mt-1 font-medium">{provenance.sources.join(", ")}</p>
            ) : (
              <p className="mt-1 text-ink/50">No source line in cache</p>
            )}
            {provenance.evidenceTotal !== null && (
              <p className="mt-1 font-mono text-xs text-ink/60">
                {provenance.evidenceTotal} evidence items ranked
              </p>
            )}
          </div>

          {provenance.footerLines.length > 0 && (
            <div>
              <p className="font-mono text-[10px] uppercase tracking-wider text-ink/50">
                Scrape stats
              </p>
              <ul className="mt-2 space-y-1 font-mono text-xs">
                {provenance.footerLines.map((line) => (
                  <li key={line}>{line}</li>
                ))}
              </ul>
            </div>
          )}

          {summary && (
            <div>
              <p className="font-mono text-[10px] uppercase tracking-wider text-ink/50">
                Gemini brief
              </p>
              <p className="mt-1">
                <span className="font-bold capitalize">{summary.sentiment}</span>
                {" · "}
                mindshare {summary.momentum_score}/100
              </p>
              {summary.themes.length > 0 && (
                <ul className="mt-2 list-inside list-disc text-ink/80">
                  {summary.themes.map((t) => (
                    <li key={t}>{t}</li>
                  ))}
                </ul>
              )}
              {summary.assets.length > 0 && (
                <p className="mt-2 font-mono text-xs">
                  Suggested:{" "}
                  {summary.assets
                    .map((a) => `${a.ticker} (${a.kind})`)
                    .join(", ")}
                </p>
              )}
            </div>
          )}

          <p className="border-t border-ink/10 pt-4 font-mono text-[10px] leading-relaxed text-ink/45">
            Evidence from last30days-skill (Reddit, YouTube, GitHub, etc.).
            Summaries generated by Gemini from that markdown. Demo runs replay
            pre-indexed cache; live runs use the same pipeline at request time.
          </p>
        </div>
      </div>
    </div>
  );
}
